⨯     `next export` has been removed in favor of 'output: export' in next.config.js. Learn more: https://nextjs.org/docs/app/building-your-application/deploying/static-exports
Error: Command "npm run build" exited with 1

This page could not be found.
404