Route (app)                                 Size  First Load JS ┌ ○ /                                    56.5 kB         173 kB └ ○ /_not-found                            977 B         102 kB + First Load JS shared by all             101 kB   ├ chunks/4bd1b696-54745a3524832e64.js  53.2 kB   ├ chunks/684-ea2b4c16f840ed49.js       45.5 kB   └ other shared chunks (total)           1.9 kB ○  (Static)  prerendered as static content  ⨯     `next export` has been removed in favor of 'output: export' in next.config.js. Learn more: https://nextjs.org/docs/app/building-your-application/deploying/static-exports
Error: Command "npm run build" exited with 1
Exiting build container